{% set version = "0.4.3" %}

package:
  name: intake
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/intake/intake-{{ version }}.tar.gz
  sha256: 80862f41d5410a4237f9b2138cacc62240f75f925a233f986c1df10a541c6f99

build:
  number: 0
  noarch: python
  entry_points:
    - intake-server = intake.cli.server.__main__:main
    - intake = intake.cli.client.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy
    - msgpack-python
    - msgpack-numpy
    - requests
    - tornado >=4.5.1
    - jinja2
    - ruamel.yaml >=0.15.0
    - dask >=0.17.0
    - python-snappy
    - appdirs
    # - holoviews
    # - ipywidgets >=7.2
    # - pandas

test:
  source_files:
    - intake
  requires:
    - pytest
  imports:
    - intake
    - intake.auth
    - intake.auth.tests
    - intake.catalog
    - intake.catalog.tests
    - intake.cli
    - intake.cli.client
    - intake.cli.client.tests
    - intake.cli.server
    - intake.cli.server.tests
    - intake.container
    - intake.gui
    - intake.source
    - intake.source.tests
    - intake.tests
  commands:
    - intake list --help
    - intake-server --help
    - pytest -rxs intake

about:
  home: https://github.com/ContinuumIO/intake
  license: BSD-2-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Data load and catalog system

extra:
  recipe-maintainers:
    - ocefpaf
    - martindurant
