{% set version = "0.6.3" %}

package:
  name: intake
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/intake/intake-{{ version }}.tar.gz
  sha256: f64543353f30d9440b953984f78b7a0954e5756d70c64243609d307ba488014f

build:
  number: 0
  noarch: python
  entry_points:
    - intake-server = intake.cli.server.__main__:main
    - intake = intake.cli.client.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - appdirs
    - entrypoints
    - jinja2
    - msgpack-python
    - numpy
    - pyyaml
    - requests
    - dask >=1.0
    # dask[bag]
    - cloudpickle >=0.2.2
    - fsspec >=0.7.4
    - toolz >=0.8.2
    - partd >=0.3.10

test:
  source_files:
    - intake
  imports:
    - intake
    - intake.auth
    - intake.catalog
    - intake.source
  commands:
    - pip check
    - intake list --help
    - intake-server --help
  requires:
    - pip

about:
  home: https://github.com/ContinuumIO/intake
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Data load and catalog system

extra:
  recipe-maintainers:
    - ocefpaf
    - martindurant
