{% set version = "2.0.8" %}

package:
  name: intake
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/intake/intake-{{ version }}.tar.gz
  sha256: 731d484a002de2f659bb988f406b35037234a35c17b08776d9a5e4838ecf2769

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - platformdirs
    - fsspec >=2023.0.0
    - pyyaml
    - networkx

test:
  source_files:
    - intake
  imports:
    - intake
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/intake/intake
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Data load and catalog system

extra:
  recipe-maintainers:
    - ocefpaf
    - martindurant
