{% set version = "2.0.3" %}

package:
  name: intake
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/intake/intake-{{ version }}.tar.gz
  sha256: 03e72ab97c74136e33f601ac6e1651a28392ded69914ac9f2fa864c4ffcfd009

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - appdirs
    - fsspec >=2023.0.0
    - pyyaml

test:
  source_files:
    - intake
  imports:
    - intake
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/intake/intake
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Data load and catalog system

extra:
  recipe-maintainers:
    - ocefpaf
    - martindurant
